// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC882UykO3J6jOEvAHLykQJB0qgyCijQJk',
    appId: '1:788573879128:web:c0a3491e906600cb34c32d',
    messagingSenderId: '788573879128',
    projectId: 'social-media-app-auth-cccca',
    authDomain: 'social-media-app-auth-cccca.firebaseapp.com',
    storageBucket: 'social-media-app-auth-cccca.firebasestorage.app',
    measurementId: 'G-0XLMZ6QJPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymDAIFHCwjBJd-Dr2q4wpz9Me0bLRTyM',
    appId: '1:788573879128:android:24344cf27f3ecbcb34c32d',
    messagingSenderId: '788573879128',
    projectId: 'social-media-app-auth-cccca',
    storageBucket: 'social-media-app-auth-cccca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HX3Cwg0OcYxn0UCuwBx-6lX_Ui5UCYY',
    appId: '1:788573879128:ios:e029b5e75ca5f34f34c32d',
    messagingSenderId: '788573879128',
    projectId: 'social-media-app-auth-cccca',
    storageBucket: 'social-media-app-auth-cccca.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HX3Cwg0OcYxn0UCuwBx-6lX_Ui5UCYY',
    appId: '1:788573879128:ios:e029b5e75ca5f34f34c32d',
    messagingSenderId: '788573879128',
    projectId: 'social-media-app-auth-cccca',
    storageBucket: 'social-media-app-auth-cccca.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC882UykO3J6jOEvAHLykQJB0qgyCijQJk',
    appId: '1:788573879128:web:de83a0056995fbe734c32d',
    messagingSenderId: '788573879128',
    projectId: 'social-media-app-auth-cccca',
    authDomain: 'social-media-app-auth-cccca.firebaseapp.com',
    storageBucket: 'social-media-app-auth-cccca.firebasestorage.app',
    measurementId: 'G-QC450MDW2T',
  );
}
